# Generated by Django 5.1.2 on 2024-10-17 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Country',
        ),
    ]
